name: fractal_invest

services:
  app:
    container_name: "fractal_invest_app"
    build:
      args:
        user: fractal_invest
        uid: 1000
      context: ./.dockerfiles
      dockerfile: Dockerfile
    # image: fractal_invest
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.dockerfiles/php.ini:/usr/local/etc/php/php.ini
    networks:
      - fractal_invest
    environment:
      - TZ=Asia/Dhaka

  nginx:
    image: nginx:alpine
    container_name: "fractal_invest_nginx"
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./.dockerfiles:/etc/nginx/conf.d/
    networks:
      - fractal_invest
    environment:
      - TZ=Asia/Dhaka

  redis:
    image: redis:alpine
    container_name: fractal_invest_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - fractal_invest
    environment:
      - TZ=Asia/Dhaka

  db:
    image: mysql:8.4
    container_name: fractal_invest_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fractal_db
      MYSQL_USER: fractal_user
      MYSQL_PASSWORD: fractal_password
    networks:
      - fractal_invest

networks:
  fractal_invest:
    driver: bridge
