name: fractal_invest

services:
  app:
    container_name: "fractal_invest_app"
    ports:
      - "5173:5173"
    build:
      args:
        user: fractal_invest
        uid: 1000
      context: ./.dockerfiles
      dockerfile: Dockerfile
    # image: fractal_invest
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.dockerfiles/php.ini:/usr/local/etc/php/php.ini
    networks:
      - fractal_invest
    environment:
      - TZ=Asia/Dhaka

  nginx:
    image: nginx:alpine
    container_name: "fractal_invest_nginx"
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./.dockerfiles:/etc/nginx/conf.d/
    networks:
      - fractal_invest
    environment:
      - TZ=Asia/Dhaka

  redis:
    image: redis:alpine
    container_name: fractal_invest_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - fractal_invest
    environment:
      - TZ=Asia/Dhaka

  cron:
    container_name: fractal_invest_cron
    build:
      args:
        user: fractal_invest
        uid: 1000
      context: ./.dockerfiles
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - fractal_invest
    environment:
      SERVICE_NAME: fractal_invest
      SERVICE_TAGS: dev
      DB_CONNECTION:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-3306}:3306
      DB_DATABASE: ${DB_DATABASE:-fractal_invest}
      DB_USERNAME: ${DB_USERNAME:-fractal_invest}
      DB_PASSWORD: ${DB_PASSWORD:-fractal_invest}

  db:
    image: mysql:8.4
    container_name: fractal_invest_db
    restart: always
    volumes:
      - ./.dockerfiles/dbdata:/var/lib/mysql
      - ./.dockerfiles/my.cnf:/etc/mysql/my.cnf
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-fractal_invest}
      MYSQL_USER: ${DB_USERNAME:-fractal_invest}
      MYSQL_PASSWORD: ${DB_PASSWORD:-fractal_invest}
    networks:
      - fractal_invest

networks:
  fractal_invest:
    driver: bridge

volumes:
  dbdata:
    driver: local
